kafka:
  clusters:
    - name: local
      bootstrapServers: localhost:9092
      zookeeper: localhost:2181
      schemaRegistry: http://localhost:8081
      ksqldbServer: http://localhost:8088
      kafkaConnect:
        - name: first
          address: http://localhost:8083
      metrics:
        port: 9997
        type: JMX
spring:
  jmx:
    enabled: true
auth:
  type: DISABLED
#server:
#  port: 8080 #- Port in which kafka-ui will run.